#
# Created by GuHaijun on 2023/6/26.
#

LIBJPEG_TURBO_USER_LOCAL_PATH:=$(LOCAL_PATH)

LIBJPEG_TURBO_USER_LOCAL_C_INCLUDES:=$(LOCAL_C_INCLUDES)
LIBJPEG_TURBO_USER_LOCAL_CFLAGS:=$(LOCAL_CFLAGS)
LIBJPEG_TURBO_USER_LOCAL_STATIC_LIBRARIES:=$(LOCAL_STATIC_LIBRARIES)
LIBJPEG_TURBO_USER_LOCAL_SHARED_LIBRARIES:=$(LOCAL_SHARED_LIBRARIES)
LIBJPEG_TURBO_USER_LOCAL_LDLIBS:=$(LOCAL_LDLIBS)
LIBJPEG_TURBO_USER_LOCAL_MODULE_FILENAME:=$(LOCAL_MODULE_FILENAME)

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

# LIBJPEG_TURBO_LIB_TYPE := STATIC
ifeq ($(LIBJPEG_TURBO_LIB_TYPE),)
    LIBJPEG_TURBO_LIB_TYPE := SHARED
endif

LIBJPEG_TURBO_C_INCLUDES_DIR := $(LOCAL_PATH)/include
LIBJPEG_TURBO_LIBS_DIR := lib/$(TARGET_ARCH_ABI)

LIBJPEG_TURBO_STATIC_LIBS := jpeg_static \
    turbojpeg_static \
    jpeg12_static \
    jpeg16_static \
    turbojpeg12_static \
    turbojpeg16_static \

LIBJPEG_TURBO_SHARED_LIBS := jpeg \
    turbojpeg \

ifeq ($(LIBJPEG_TURBO_LIB_TYPE), STATIC)
    LIBJPEG_TURBO_LIB_SUFFIX := .a
    
    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg12_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg16_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg12_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg16_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

else 
    LIBJPEG_TURBO_LIB_SUFFIX := .so

    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_C_INCLUDES_DIR)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
endif

include $(CLEAR_VARS)

LOCAL_C_INCLUDES:=$(LIBJPEG_TURBO_USER_LOCAL_C_INCLUDES)
LOCAL_CFLAGS:=$(LIBJPEG_TURBO_USER_LOCAL_CFLAGS)
LOCAL_STATIC_LIBRARIES:=$(LIBJPEG_TURBO_USER_LOCAL_STATIC_LIBRARIES)
LOCAL_SHARED_LIBRARIES:=$(LIBJPEG_TURBO_USER_LOCAL_SHARED_LIBRARIES)
LOCAL_LDLIBS:=$(LIBJPEG_TURBO_USER_LOCAL_LDLIBS)
LOCAL_MODULE_FILENAME:=$(LIBJPEG_TURBO_USER_LOCAL_MODULE_FILENAME)

LOCAL_C_INCLUDES += $(LIBJPEG_TURBO_C_INCLUDES_DIR)
ifeq ($(LIBJPEG_TURBO_LIB_TYPE), STATIC)
LOCAL_STATIC_LIBRARIES += $(LIBJPEG_TURBO_STATIC_LIBS)
else
LOCAL_SHARED_LIBRARIES += $(LIBJPEG_TURBO_SHARED_LIBS)
endif

LOCAL_PATH:=$(LIBJPEG_TURBO_USER_LOCAL_PATH)