#
# Created by GuHaijun on 2023/6/26.
#

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

# LIBJPEG_TURBO_LIB_TYPE := STATIC
ifeq ($(LIBJPEG_TURBO_LIB_TYPE),)
    LIBJPEG_TURBO_LIB_TYPE := SHARED
endif

$(warning LIBJPEG_TURBO_LIB_TYPE: $(LIBJPEG_TURBO_LIB_TYPE))

LIBJPEG_TURBO_LOCAL_STATIC_LIBRARIES :=
LIBJPEG_TURBO_LOCAL_SHARED_LIBRARIES :=

LIBJPEG_TURBO_LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/include \

LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_C_INCLUDES)

LIBJPEG_TURBO_LIBS_DIR := lib/$(TARGET_ARCH_ABI)

ifeq ($(LIBJPEG_TURBO_LIB_TYPE), STATIC)
    LIBJPEG_TURBO_LIB_SUFFIX := .a
    
    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg12_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg16_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg12_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg16_static
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

else 
    LIBJPEG_TURBO_LIB_SUFFIX := .so

    include $(CLEAR_VARS)
    LOCAL_MODULE := jpeg
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)

    include $(CLEAR_VARS)
    LOCAL_MODULE := turbojpeg
    LOCAL_SRC_FILES := $(LIBJPEG_TURBO_LIBS_DIR)/lib$(LOCAL_MODULE)$(LIBJPEG_TURBO_LIB_SUFFIX)
    LOCAL_EXPORT_C_INCLUDES := $(LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES)
    ifeq ($(filter $(modules-get-list), $(LOCAL_MODULE)),)
        include $(PREBUILT_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARY)
    endif
    LIBJPEG_TURBO_LOCAL_$(LIBJPEG_TURBO_LIB_TYPE)_LIBRARIES += $(LOCAL_MODULE)
endif
