#
# Created by GuHaijun on 2023/6/25.
#

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

# LIBJPEG_TURBO_LIB_TYPE := STATIC
ifeq ($(LIBJPEG_TURBO_LIB_TYPE),)
    LIBJPEG_TURBO_LIB_TYPE := SHARED
endif

$(warning LIBJPEG_TURBO_LIB_TYPE: $(LIBJPEG_TURBO_LIB_TYPE))

LIBJPEG_TURBO_LOCAL_STATIC_LIBRARIES :=
LIBJPEG_TURBO_LOCAL_SHARED_LIBRARIES :=

include $(LOCAL_PATH)/jpeg.mk
include $(LOCAL_PATH)/turbojpeg.mk

LIBJPEG_TURBO_LOCAL_C_INCLUDES :=  $(addprefix $(LOCAL_PATH)/, $(JPEG_TURBO_C_INCLUDES))
LIBJPEG_TURBO_LOCAL_EXPORT_C_INCLUDES :=  $(addprefix $(LOCAL_PATH)/, $(JPEG_TURBO_EXPORT_C_INCLUDES))
